name: CI - jan-inference-model

on:
  push:
    branches:
      - dev
    paths:
      - "apps/jan-inference-model/**"
      - .github/workflows/dev-jan-inference-model
      - .github/workflows/template-docker.yml
  pull_request:
    branches:
      - dev
    paths:
      - "apps/jan-inference-model/**"
      - .github/workflows/dev-jan-inference-model
      - .github/workflows/template-docker.yml

jobs:
  build-docker-x64:
    uses: ./.github/workflows/template-docker.yml
    secrets: inherit
    with:
      runs-on: ubuntu-24-04-docker
      docker-file: apps/jan-inference-model/Dockerfile
      context: apps/jan-inference-model
      registry-url: registry.menlo.ai
      tags: registry.menlo.ai/jan-server/jan-inference-model:dev-${{ github.sha }}
      is_push: ${{ github.event_name == 'push' }}
