name: CI - jan-server

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-docker-x64:
    strategy:
      fail-fast: true
      matrix:
        include:
          - docker-file: apps/jan-api-gateway/Dockerfile
            context: apps/jan-api-gateway
            registry-url: registry.menlo.ai
            tags: registry.menlo.ai/jan-server/jan-api-gateway:${{ github.ref_name }}
            is_push: true
    uses: ./.github/workflows/template-docker.yml
    secrets: inherit
    with:
      runs-on: ubuntu-24-04-docker
      docker-file: ${{ matrix.docker-file }}
      context: ${{ matrix.context }}
      registry-url: ${{ matrix.registry-url }}
      tags: ${{ matrix.tags }}
      is_push: ${{ matrix.is_push }}