name: CI - jan-api-gateway
on:
  push:
    branches:
      - stag
    paths:
      - "apps/jan-api-gateway/**"
      - .github/workflows/stag.yaml
      - .github/workflows/template-docker.yml

jobs:
  build-docker-x64:
    uses: ./.github/workflows/template-docker.yml
    secrets: inherit
    with:
      runs-on: ubuntu-24-04-docker
      docker-file: apps/jan-api-gateway/Dockerfile
      context: apps/jan-api-gateway
      registry-url: registry.menlo.ai
      tags: registry.menlo.ai/jan-server/jan-api-gateway:stag-${{ github.sha }}
      is_push: ${{ github.event_name == 'push' }}
      build-args: |
        VERSION_TAG=stag-${{ github.sha }}
